version: "3.7"
services: 
  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq-container
      restart: always
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - ./rabbitmq/dados:/var/lib/rabbitmq/
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
  db: 
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./api/db/data:/var/lib/mysql
    restart: always
  api: 
    build: "./api"
    container_name: node-container
    restart: always 
    volumes:
      - ./api:/home/node/app
    ports:
      - "9001:9001"
    depends_on:
      - db
  web:
    image: "php:7.2-apache"
    container_name: php-container
    restart: always
    volumes:
      - ./web:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - db
      - api
      - rabbitmq